LibraryHandler3/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryHandler3.Models
{
    public class Book
    {
        public int BookId { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
    }
}

LibraryHandler3/Models/LibraryHandlerContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace LibraryHandler3.Models
{
    public class LibraryHandlerContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public LibraryHandlerContext() : base("name=LibraryHandler3Context")
        {
        }

        public System.Data.Entity.DbSet<LibraryHandler3.Models.Book> Books { get; set; }
    }
}

LibraryHandler3/Controllers/LibraryBooksController.cs
using LibraryHandler3.Models;
using LibraryHandler3.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace LibraryHandler3.Controllers
{
    public class LibraryBooksController : ApiController
    {
        IUnitOfWork _unitOfWork;
        public LibraryBooksController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IHttpActionResult GetBooks()
        {
            return Ok(_unitOfWork.Books.GetAll());
        }
        [HttpPost]
        public IHttpActionResult AddBook(Book book)
        {
            _unitOfWork.Books.Add(book);
            try
            {
                _unitOfWork.SaveChanges();
            }
            catch
            {
                return BadRequest();
            }
            return Ok(book.BookId);
        }
        [HttpPut]
        public IHttpActionResult UpdateBook(Book book)
        {
            _unitOfWork.Books.Edit(book);
            try
            {
                _unitOfWork.SaveChanges();
            }
            catch
            {
                return BadRequest();
            }
            return Ok();
        }
        [HttpDelete]
        public IHttpActionResult DeleteBook(int id)
        {
            var book = _unitOfWork.Books.Find(id);
            if (book==null)
            {
                return NotFound();
            }
            _unitOfWork.Books.Delete(book);
            _unitOfWork.SaveChanges();
            return Ok();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

LibraryHandler3/Controllers/LibraryController.cs
using LibraryHandler3.Data;
using LibraryHandler3.Models;
using LibraryHandler3.Repository.Interfaces;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace LibraryHandler3.Controllers
{
    public class LibraryController : Controller
    {
        IHttpRestService _restService;
        public LibraryController(IHttpRestService restService)
        {
            _restService = restService;
        }

        public string Adress;

        private string adress
        {
            get
            {
                if (String.IsNullOrEmpty(Adress))
                {
                    return Request.Url.Scheme + "://" + Request.Url.Authority + "/api/LibraryBooks/GetBooks";
                }
                else
                {
                    return Adress;
                }
            }
            set
            {
                Adress = adress;
            }

        }

        public async Task<ActionResult> Index()
        {
            _restService.Adress = adress;
            try
            {
                var books = await _restService.GetBooks();
                if (books != null)
                {
                    return View(books);
                }
                else
                {
                    return new HttpStatusCodeResult(_restService.StatusCode);
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _restService.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

LibraryHandler3/Views/Library/Index.cshtml
@model IEnumerable<LibraryHandler3.Models.Book>
@{
    ViewBag.Title = "Home Page";
}
<br />
<form>
<table class="table-bordered" id="BookTable">
    <tr>
        <th>Nazwa</th>
        <th>Autor</th>
    </tr>
    @foreach(var book in Model)
    {
        <tr id="@book.BookId">
            
            <td class="author">@book.Author</td>
            <td class="name">@book.Name</td>
            <td>
                <div class="btn btn-danger deleteBtn" onclick="DeleteBook(@book.BookId)">Usuń</div>
                <div class="btn btn-info editBtn" onclick="EditBook(@book.BookId)">Edycja</div>
            </td>
        </tr>
        
    }
    <tr>
        <td class="author"><input type="text" id="NewAuthor"/></td>
        <td class="name"><input type="text" id="NewName" /></td>
        <td>
            <div class="btn btn-success" onclick="NewBook()">Dodaj nową książkę</div>
        </td>
    </tr>
</table>
</form>
@section Scripts{
    <script type="text/javascript">
        function DeleteBook(id) {
            $.ajax({
                type: 'DELETE',
                url: "/api/LibraryBooks/DeleteBook/"+id,
                contentType: 'application/json',
                success: function (data) {
                    $("#" + id).remove();
                },
                error: function (error) {
                    console.log(error);
                    alert("Operacja nie udała się");
                }
            })

        }
        var arrayOfEditions=[];
        function EditBook(id) {
            var editedRow = $("#" + id);
            var authorCell = $(editedRow).find(".author")[0];
            var nameCell = $(editedRow).find(".name")[0];
            var editButtonCell = $(editedRow).find(".editBtn")[0];
            var deleteButtonCell = $(editedRow).find(".deleteBtn")[0];
            var authorValue = $(authorCell).text();
            var nameValue = $(nameCell).text();
            var editedBook = {
                BookId: id,
                Name: nameValue,
                Author: authorValue
            }
            arrayOfEditions.push(editedBook);
            $(authorCell).empty().append("<input type='text' class='author' value='" + authorValue + "'></input>");
            $(nameCell).empty().append("<input type='text' class='name' value='" + nameValue + "'></input>");
            $(editButtonCell).attr("onclick", "ConfirmEdition(" + id + ")").text("Zapisz");
            $(deleteButtonCell).attr("onclick", "RemoveChanges(" + id + ")").text("Anuluj");
        }

        function ConfirmEdition(id) {
            var editedRow = $("#" + id);
            var authorCell = $(editedRow).find(".author")[0];
            var nameCell = $(editedRow).find(".name")[0];
            var authorValue = $(authorCell).find("input").val();
            var nameValue = $(nameCell).find("input").val();
            var editedBook = {
                BookId: id,
                Name: nameValue,
                Author: authorValue
            };
            $.ajax({
                type: 'PUT',
                url: '/api/LibraryBooks/UpdateBook',
                data: JSON.stringify(editedBook),
                contentType: 'application/json',
                success: function () {
                    ReturnBookRowValuesToNormal(editedRow, editedBook);
                },
                error: function (error) {
                    console.log(error);
                    alert("Operacja nie udała się");
                }
            });
        }
        function RemoveChanges(id) {
            var editedRow = $("#" + id);
            //var authorCell = $(editedRow).find(".author")[0];
            //var nameCell = $(editedRow).find(".name")[0];
            //var editButtonCell = $(editedRow).find(".editBtn")[0];
            //var deleteButtonCell = $(editedRow).find(".deleteBtn")[0];
            var editedBook = arrayOfEditions.find(x=>x.Id == id);
            //$(authorCell).empty().text(editedBook.Author);
            //$(nameCell).empty().text(editedBook.Name);
            //$(editButtonCell).attr("onclick", "EditBook(" + id + ")").text("Edycja");
            //$(deleteButtonCell).attr("onclick", "DeleteBook(" + id + ")").text("Usuń");
            ReturnBookRowValuesToNormal(editedRow, editedBook);

        }
        function ReturnBookRowValuesToNormal(editedRow, book) {
            var authorCell = $(editedRow).find(".author")[0];
            var nameCell = $(editedRow).find(".name")[0];
            var editButtonCell = $(editedRow).find(".editBtn")[0];
            var deleteButtonCell = $(editedRow).find(".deleteBtn")[0];
            $(authorCell).empty().text(book.Author);
            $(nameCell).empty().text(book.Name);
            $(editButtonCell).attr("onclick", "EditBook(" + book.BookId + ")").text("Edycja");
            $(deleteButtonCell).attr("onclick", "DeleteBook(" + book.BookId + ")").text("Usuń");

        }

        function NewBook() {
            var book = {
                Author: $("#NewAuthor").val(),
                Name: $("#NewName").val(),

            };
            $.ajax({
                type:'POST',
                url: '/api/LibraryBooks/AddBook',
                data: JSON.stringify(book),
                contentType:'application/json',
                success:function(bookId){
                    $("#BookTable tr:last").before("<tr id='" + bookId + "'><td class='author'>" + book.Author + "</td><td class='name'>" + book.Name + "</td>" +
                        "<td><div class='btn btn-danger deleteBtn' onclick='DeleteBook(" + bookId + ")'>Usuń</div>"+
                        "<div class='btn btn-info editBtn' onclick='EditBook(" + bookId + ")'>Edycja</div></td>");
                    $("#NewAuthor").val("");
                    $("#NewName").val("");
                },
                error: function (error) {
                    console.log(error);
                    alert("Operacja nie udała się");
                }
            });
        }
    </script>
    }

LibraryHandler3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Obsługa biblioteki", "Index", "Library", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LibraryHandler</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>